project:
  type: book
  output-dir: docs

book:
  title: "Remote Sensing Portfolio"
  author: "Emily Dugmore"
  date: "1/20/2026"
  chapters:
    - index.qmd
    - 1_RS_intro.qmd
    - 3_Corrections.qmd
    - 4_policy.qmd
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

